version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://indoor_user:indoor_pass@db:5432/indoor_app
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=indoor_user
      - POSTGRES_PASSWORD=indoor_pass
      - POSTGRES_DB=indoor_app

volumes:
  postgres_data: